#---------------------------------------------------#
# åŸºç¡€é…ç½®
#---------------------------------------------------#
port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

#---------------------------------------------------#
# èŠ‚ç‚¹åˆ—è¡¨ (è¯·ç¡®ä¿è¿™é‡Œçš„ç¼©è¿›æ˜¯ä¸¤ä¸ªç©ºæ ¼)
#---------------------------------------------------#
proxies:
  - { name: 'ğŸ‡­ğŸ‡° é¦™æ¸¯_01', type: ss, server: ft-hk-xygh-by.51feitu.com, port: 10001, cipher: chacha20-ietf-poly1305, password: 6a8ce4f5-5450-4bcd-bde5-2ed046b2d38c, udp: true }
  - { name: 'ğŸ‡­ğŸ‡° é¦™æ¸¯_02', type: vmess, server: ft-hk-xygh-by.51feitu.com, port: 10002, uuid: 6a8ce4f5-5450-4bcd-bde5-2ed046b2d38c, alterId: 0, cipher: auto, udp: true, network: ws }
  - { name: 'ğŸ‡­ğŸ‡° é¦™æ¸¯_03', type: ss, server: ft-hk-xygh-by.51feitu.com, port: 10003, cipher: chacha20-ietf-poly1305, password: 6a8ce4f5-5450-4bcd-bde5-2ed046b2d38c, udp: true }
  - { name: 'ğŸ‡­ğŸ‡° ä¸‰ç½‘Ã—2-é¦™æ¸¯_04', type: vmess, server: ft-hk-xygh-pro.51feitu.com, port: 20004, uuid: 6a8ce4f5-5450-4bcd-bde5-2ed046b2d38c, alterId: 0, cipher: auto, udp: true, network: ws }
  - { name: 'ğŸ‡­ğŸ‡° ä¸‰ç½‘Ã—2-é¦™æ¸¯_05', type: ss, server: ft-hk-xygh-pro.51feitu.com, port: 20005, cipher: chacha20-ietf-poly1305, password: 6a8ce4f5-5450-4bcd-bde5-2ed046b2d38c, udp: true }
  - { name: 'ğŸ‡­ğŸ‡° ä¸‰ç½‘Ã—2-é¦™æ¸¯_06', type: vmess, server: ft-hk-xygh-pro.51feitu.com, port: 20006, uuid: 6a8ce4f5-5450-4bcd-bde5-2ed046b2d38c, alterId: 0, cipher: auto, udp: true, network: ws }
  - { name: 'ğŸ‡­ğŸ‡° ä¸‰ç½‘Ã—2-é¦™æ¸¯_07', type: ss, server: ft-hk-xygh-pro.51feitu.com, port: 20007, cipher: chacha20-ietf-poly1305, password: 6a8ce4f5-5450-4bcd-bde5-2ed046b2d38c, udp: true }
  - { name: 'ğŸ‡­ğŸ‡° ä¸‰ç½‘Ã—2-é¦™æ¸¯_08', type: vmess, server: ft-hk-xygh-pro.51feitu.com, port: 20008, uuid: 6a8ce4f5-5450-4bcd-bde5-2ed046b2d38c, alterId: 0, cipher: auto, udp: true, network: ws }
  - { name: 'ğŸ‡­ğŸ‡° é¦™æ¸¯_09', type: ss, server: ft-hk-xygh-by.51feitu.com, port: 10009, cipher: chacha20-ietf-poly1305, password: 6a8ce4f5-5450-4bcd-bde5-2ed046b2d38c, udp: true }
  - { name: 'ğŸ‡­ğŸ‡° é¦™æ¸¯_10', type: vmess, server: ft-hk-xygh-by.51feitu.com, port: 10010, uuid: 6a8ce4f5-5450-4bcd-bde5-2ed046b2d38c, alterId: 0, cipher: auto, udp: true, network: ws }
  - { name: 'ğŸ‡­ğŸ‡° é¦™æ¸¯_11', type: ss, server: ft-hk-xygh-by.51feitu.com, port: 11011, cipher: chacha20-ietf-poly1305, password: 6a8ce4f5-5450-4bcd-bde5-2ed046b2d38c, udp: true }
  - { name: 'ğŸ‡­ğŸ‡° é¦™æ¸¯_12', type: vmess, server: ft-hk-xygh-by.51feitu.com, port: 11012, uuid: 6a8ce4f5-5450-4bcd-bde5-2ed046b2d38c, alterId: 0, cipher: auto, udp: true, network: ws }
  - { name: 'ğŸ‡­ğŸ‡° é¦™æ¸¯_13', type: ss, server: ft-hk-xygh-by.51feitu.com, port: 11013, cipher: chacha20-ietf-poly1305, password: 6a8ce4f5-5450-4bcd-bde5-2ed046b2d38c, udp: true }
  - { name: 'ğŸ‡­ğŸ‡° é¦™æ¸¯_14', type: vmess, server: ft-hk-xygh-by.51feitu.com, port: 11014, uuid: 6a8ce4f5-5450-4bcd-bde5-2ed046b2d38c, alterId: 0, cipher: auto, udp: true, network: ws }
  - { name: 'ğŸ‡­ğŸ‡° é¦™æ¸¯_15-v6', type: ss, server: ft-hk-xygh-by.51feitu.com, port: 11015, cipher: chacha20-ietf-poly1305, password: 6a8ce4f5-5450-4bcd-bde5-2ed046b2d38c, udp: true }
  - { name: 'ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡_01', type: ss, server: ft-sg-xygh-by.51feitu.com, port: 12001, cipher: chacha20-ietf-poly1305, password: 6a8ce4f5-5450-4bcd-bde5-2ed046b2d38c, udp: true }
  - { name: 'ğŸ‡¯ğŸ‡µ æ—¥æœ¬_01', type: ss, server: ft-jp-xygh-by.51feitu.com, port: 13001, cipher: chacha20-ietf-poly1305, password: 6a8ce4f5-5450-4bcd-bde5-2ed046b2d38c, udp: true }
  - { name: 'ğŸ‡ºğŸ‡¸ ç¾å›½_01', type: ss, server: ft-us-xygh-by.51feitu.com, port: 14001, cipher: chacha20-ietf-poly1305, password: 6a8ce4f5-5450-4bcd-bde5-2ed046b2d38c, udp: true }

#---------------------------------------------------#
# ç­–ç•¥ç»„
#---------------------------------------------------#
proxy-groups:
  - name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - ğŸï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯_01
      - ğŸ‡­ğŸ‡° é¦™æ¸¯_02
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡_01
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬_01
      - ğŸ‡ºğŸ‡¸ ç¾å›½_01
      - DIRECT

  - name: ğŸï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯_01
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡_01
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬_01

#---------------------------------------------------#
# è§„åˆ™
#---------------------------------------------------#
rules:
  - GEOIP,CN,DIRECT
  - MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
